services:
    senky.groupspp.controller.select:
        class: senky\groupspp\controller\select_controller
        arguments:
            - '@controller.helper'
            - '@user'
            - '@dbal.conn'
            - '@template'
            - '@language'
            - '@request'
            - '%tables.groups%'
            - '%tables.user_group%'
            - '%core.root_path%'
            - '%core.php_ext%'

    senky.groupspp.controller.view:
        class: senky\groupspp\controller\view_controller
        arguments:
            - '@controller.helper'
            - '@user'
            - '@dbal.conn'
            - '@template'
            - '@language'
            - '@request'
            - '@cache'
            - '@config'
            - '@auth'
            - '@content.visibility'
            - '@pagination'
            - '%tables.topics%'
            - '%tables.groups%'
            - '%tables.user_group%'
            - '%tables.forums%'
            - '%tables.topics_track%'
            - '%tables.forums_track%'
            - '%tables.zebra%'
            - '%core.root_path%'
            - '%core.php_ext%'

    senky.groupspp.controller.acp:
        class: senky\groupspp\controller\acp_controller
        arguments:
            - '@language'
            - '@request'
            - '@template'
            - '@dbal.conn'
            - '@cache.driver'
            - '%tables.forums%'
            - '%tables.groups%'
            - '%core.root_path%'
            - '%core.php_ext%'

    senky.groupspp.listener:
        class: senky\groupspp\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
