services:
    senky.groupspp.controller.main:
        class: senky\groupspp\controller\main_controller
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'

    senky.groupspp.controller.acp:
        class: senky\groupspp\controller\acp_controller
        arguments:
            - '@language'
            - '@request'
            - '@template'
            - '@dbal.conn'
            - '@cache.driver'
            - '%tables.forums%'
            - '%tables.groups%'
            - '%core.root_path%'
            - '%core.php_ext%'

    senky.groupspp.listener:
        class: senky\groupspp\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
